### ISSUE TITLE
 visualize on ubuntu

### ISSUE THREAD

**Issue by CPZCPZ** [Kei18/tswap#17]
Sorry to bother you, your work is so pretty! But could you please give some guidance on how to visualize on ubuntu20(I don't know if it has something to do with the version)? thank you in advance

**Comment by Kei18** [comment]
Hi,

I have never tried the visualizer on Ubuntu. But I think it is possible by changing the installation procedure of openFrameworks. Please refer to the following site.
https://openframeworks.cc/setup/linux-install/


Maybe changing the first line of the following script (for macOS) is sufficient.
```sh
bash ./third_party/openFrameworks/scripts/osx/download_libs.sh
cd visualizer
make build
```

I also want to know, so let me know if it works.

Cheers,
Kei

**Comment by CPZCPZ** [comment]
Hi,
I had installed and complied the openFrameworks on my ubuntu, and then I tried to follow your step to visualize, but I failed to complete. Because I am not familiar with bash script. And I found a error in download libs related to openFrameworks. After wget statement, the link should be `ci.openframeworks.cc/libs/openFrameworksLibs_master_linux64gcc6.tar.bz2` in my computer. Although I fix that problem on my own, but **visualize** part of this readme of this project trouble me a lot between osx and ubuntu. So i quit it.
Anyway, thank you very much for your reply !
Best,
cpz

**Comment by Kei18** [comment]
Hi cpz, 

Thank you for your kind report! 

Hmm, then I need to investigate the visualizer on Ubuntu. But unfortunately, I do not think I can do it for a while (several months).

Anyway, I keep this in mind and pin this Github issue. Thanks again for your cooperation.

Best, 
Kei

**Comment by Kei18** [comment]
Check https://github.com/kei18/mapf-visualizer
